/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  Error,
  ListPetsNestedArrayParams,
  PetsNestedArray
} from '../../model';





/**
 * @summary List all pets as nested array
 */
export const listPetsNestedArray = (
    params?: ListPetsNestedArrayParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PetsNestedArray>> => {
    
    
    return axios.get(
      `/pets-nested-array`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getListPetsNestedArrayQueryKey = (params?: ListPetsNestedArrayParams,) => {
    return [`/pets-nested-array`, ...(params ? [params]: [])] as const;
    }

    
export const getListPetsNestedArrayQueryOptions = <TData = Awaited<ReturnType<typeof listPetsNestedArray>>, TError = AxiosError<Error>>(params?: ListPetsNestedArrayParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPetsNestedArray>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPetsNestedArrayQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPetsNestedArray>>> = ({ signal }) => listPetsNestedArray(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPetsNestedArray>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPetsNestedArrayQueryResult = NonNullable<Awaited<ReturnType<typeof listPetsNestedArray>>>
export type ListPetsNestedArrayQueryError = AxiosError<Error>


export function useListPetsNestedArray<TData = Awaited<ReturnType<typeof listPetsNestedArray>>, TError = AxiosError<Error>>(
 params: undefined |  ListPetsNestedArrayParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPetsNestedArray>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPetsNestedArray>>,
          TError,
          Awaited<ReturnType<typeof listPetsNestedArray>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPetsNestedArray<TData = Awaited<ReturnType<typeof listPetsNestedArray>>, TError = AxiosError<Error>>(
 params?: ListPetsNestedArrayParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPetsNestedArray>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPetsNestedArray>>,
          TError,
          Awaited<ReturnType<typeof listPetsNestedArray>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPetsNestedArray<TData = Awaited<ReturnType<typeof listPetsNestedArray>>, TError = AxiosError<Error>>(
 params?: ListPetsNestedArrayParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPetsNestedArray>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all pets as nested array
 */

export function useListPetsNestedArray<TData = Awaited<ReturnType<typeof listPetsNestedArray>>, TError = AxiosError<Error>>(
 params?: ListPetsNestedArrayParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPetsNestedArray>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPetsNestedArrayQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



